"""`kawika db`: migrations, resets, and seed data.

    kawika db migrate          Apply pending migrations
    kawika db fresh [--seed]   Drop everything, migrate from scratch (optionally seed)
    kawika db seed             Insert demo and sample data (idempotent)
    kawika db status           Revisions and row counts
    kawika db rollback         Undo the last migration(s)
    kawika db reset            Undo every migration
    kawika db make-migration   Autogenerate a migration from model changes
    kawika db check            Fail if models and migrations differ
"""

import sys
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import dataclass
from enum import StrEnum
from typing import Annotated

import typer
from alembic.util import AutogenerateDiffsDetected, CommandError
from rich.table import Table
from sqlalchemy import Engine, create_engine, pool
from sqlalchemy.exc import OperationalError
from sqlalchemy.orm import Session

from app.cli.output import console, fail, info, success, warn
from app.core.config import settings
from app.db import migrations
from app.db.maintenance import DatabaseBusyError, database_name, describe_url, drop_all_objects, table_row_counts
from app.db.seeders import SEEDERS, SeederError, SeedOptions, run_seeders, select_seeders
from app.db.session import resolve_database_url

app = typer.Typer(
    name="db",
    help="Migrations, resets, and seed data.",
    no_args_is_help=True,
    rich_markup_mode="rich",
)


class Target(StrEnum):
    default = "default"
    test = "test"


@dataclass(frozen=True)
class DbTarget:
    name: Target
    url: str

    @property
    def label(self) -> str:
        return describe_url(self.url)

    @property
    def is_protected(self) -> bool:
        """The real application database in production."""
        return settings.is_production and self.name is Target.default


ForceOption = Annotated[bool, typer.Option("--force", "-f", help="Skip the confirmation prompt.")]


@app.callback()
def db(
    ctx: typer.Context,
    database: Annotated[
        Target | None,
        typer.Option(
            "--database",
            "-d",
            help="[b]default[/b] uses DATABASE_URL, [b]test[/b] uses TEST_DATABASE_URL. "
            "Defaults to test when APP_ENV=test.",
        ),
    ] = None,
) -> None:
    """Migrations, resets, and seed data."""
    name = database or (Target.test if settings.app_env == "test" else Target.default)
    try:
        url = resolve_database_url(name.value)
    except RuntimeError as exc:
        fail(str(exc), hint="Add it to server/.env.")
    if name is Target.test and not database_name(url).endswith("_test"):
        fail(
            f"Refusing to use '{database_name(url)}' as the test database.",
            hint="TEST_DATABASE_URL must point to a database whose name ends in _test.",
        )
    ctx.obj = DbTarget(name, url)


# Helpers -----------------------------------------------------------------


@contextmanager
def connect(target: DbTarget) -> Iterator[Engine]:
    engine = create_engine(target.url, poolclass=pool.NullPool, connect_args={"connect_timeout": 5})
    try:
        with engine.connect():
            pass
    except OperationalError as exc:
        engine.dispose()
        reason = str(exc.orig).strip().splitlines()[0] if exc.orig else str(exc)
        fail(
            f"Can't connect to {target.label}: {reason}",
            hint="Check that PostgreSQL is running and the URL in server/.env is correct.",
        )
    try:
        yield engine
    finally:
        engine.dispose()


def header(target: DbTarget, action: str) -> None:
    console().print(
        f"[bold]{action}[/bold] [cyan]{target.label}[/cyan] "
        f"[dim]({target.name.value} database, APP_ENV={settings.app_env})[/dim]"
    )


def interactive() -> bool:
    """Whether a person can answer a prompt (false in CI, pipes, and tests)."""
    return sys.stdin.isatty()


def refuse_protected(target: DbTarget, action: str, force: bool) -> None:
    """Destructive commands never touch the production database without --force."""
    if target.is_protected and not force:
        fail(
            f"Refusing to {action} the production database.",
            hint="Re-run with --force if you are certain.",
        )


def confirm_destructive(target: DbTarget, action: str, force: bool) -> None:
    """Laravel-style guard: production needs --force, elsewhere ask first."""
    refuse_protected(target, action, force)
    if force:
        return
    if not interactive():
        fail(f"This will {action} {target.label}.", hint="Pass --force to run without a prompt.")
    if not typer.confirm(f"This will {action} {target.label}. Continue?", default=False):
        warn("Cancelled. Nothing was changed.")
        raise typer.Exit(1)


def state_or_fail(engine: Engine, config) -> migrations.MigrationState:
    try:
        return migrations.migration_state(engine, config)
    except LookupError as exc:
        fail(str(exc), hint="Run `kawika db fresh` to rebuild this database from the current migrations.")


def print_revisions(scripts, verb: str) -> None:
    for script in scripts:
        info(f"{verb} [cyan]{script.revision}[/cyan] {script.doc}")


def seed_database(target: DbTarget, engine: Engine, names: list[str] | None, learners: int) -> None:
    app_env = "production" if target.is_protected else ("test" if target.name is Target.test else settings.app_env)
    try:
        seeders = select_seeders(names, app_env)
    except SeederError as exc:
        fail(str(exc))

    with Session(engine) as session:
        outcomes = run_seeders(session, seeders, SeedOptions(learners=learners))

    table = Table(show_edge=False, pad_edge=False, box=None, header_style="bold")
    table.add_column("Seeder")
    table.add_column("Created", justify="right")
    table.add_column("Skipped", justify="right")
    for outcome in outcomes:
        table.add_row(outcome.name, str(outcome.result.created), str(outcome.result.skipped))
    console().print(table)
    for outcome in outcomes:
        for note in outcome.result.notes:
            info(note)
    success(f"Seeded {sum(o.result.created for o in outcomes)} rows.")


# Commands ----------------------------------------------------------------


@app.command()
def migrate(
    ctx: typer.Context,
    to: Annotated[str, typer.Option("--to", help="Target revision.")] = "head",
    seed: Annotated[bool, typer.Option("--seed", help="Run seeders afterwards.")] = False,
) -> None:
    """Apply pending migrations."""
    target: DbTarget = ctx.obj
    header(target, "Migrating")
    config = migrations.alembic_config(target.url, quiet=True)
    with connect(target) as engine:
        before = state_or_fail(engine, config)
        if before.up_to_date and to == "head":
            success(f"Already up to date at [cyan]{before.current}[/cyan].")
        else:
            try:
                migrations.upgrade(config, to)
            except CommandError as exc:
                fail(f"Migration failed: {exc}")
            after = state_or_fail(engine, config)
            applied = [s for s in after.applied if s not in before.applied]
            print_revisions(applied, "Applied")
            success(f"Migrated to [cyan]{after.current}[/cyan] ({len(applied)} applied).")
        if seed:
            seed_database(target, engine, None, SeedOptions.learners)


@app.command()
def fresh(
    ctx: typer.Context,
    seed: Annotated[bool, typer.Option("--seed", help="Run seeders afterwards.")] = False,
    learners: Annotated[int, typer.Option(min=0, max=1000, help="Sample learners to create with --seed.")] = SeedOptions.learners,
    force: ForceOption = False,
) -> None:
    """Drop [b]every[/b] table, view, sequence, and type, then migrate from scratch."""
    target: DbTarget = ctx.obj
    header(target, "Rebuilding")
    confirm_destructive(target, "drop all data in", force)
    config = migrations.alembic_config(target.url, quiet=True)
    with connect(target) as engine:
        try:
            report = drop_all_objects(engine)
        except DatabaseBusyError as exc:
            fail(str(exc))
        info(
            f"Dropped {len(report.tables)} tables, {len(report.views)} views, "
            f"{len(report.sequences)} sequences, {len(report.types)} types."
        )
        migrations.upgrade(config, "head")
        state = state_or_fail(engine, config)
        print_revisions(state.applied, "Applied")
        success(f"Fresh database at [cyan]{state.current}[/cyan].")
        if seed:
            seed_database(target, engine, None, learners)


@app.command()
def seed(
    ctx: typer.Context,
    seeder: Annotated[
        list[str] | None,
        typer.Option("--seeder", "-s", help=f"Run only these seeders (repeatable). Available: {', '.join(SEEDERS)}."),
    ] = None,
    learners: Annotated[int, typer.Option(min=0, max=1000, help="Sample learners to create.")] = SeedOptions.learners,
) -> None:
    """Insert demo and sample data. Safe to run repeatedly: existing rows are skipped."""
    target: DbTarget = ctx.obj
    header(target, "Seeding")
    config = migrations.alembic_config(target.url, quiet=True)
    with connect(target) as engine:
        state = state_or_fail(engine, config)
        if not state.up_to_date:
            fail(
                f"The database has {len(state.pending)} pending migration(s).",
                hint="Run `kawika db migrate` first.",
            )
        seed_database(target, engine, seeder, learners)


@app.command()
def status(ctx: typer.Context) -> None:
    """Show applied and pending migrations and row counts."""
    target: DbTarget = ctx.obj
    header(target, "Status of")
    config = migrations.alembic_config(target.url, quiet=True)
    with connect(target) as engine:
        state = state_or_fail(engine, config)
        counts = table_row_counts(engine)

    revisions = Table(show_edge=False, pad_edge=False, box=None, header_style="bold")
    revisions.add_column("Revision")
    revisions.add_column("Migration")
    revisions.add_column("State")
    for script in state.applied:
        revisions.add_row(script.revision, script.doc, "[green]applied[/green]")
    for script in state.pending:
        revisions.add_row(script.revision, script.doc, "[yellow]pending[/yellow]")
    console().print(revisions)

    if state.up_to_date:
        success(f"Up to date at [cyan]{state.current}[/cyan].")
    else:
        warn(f"{len(state.pending)} pending migration(s). Run `kawika db migrate`.")

    if counts:
        tables = Table(show_edge=False, pad_edge=False, box=None, header_style="bold")
        tables.add_column("Table")
        tables.add_column("Rows", justify="right")
        for name, rows in counts.items():
            tables.add_row(name, str(rows))
        console().print(tables)
    else:
        info("No tables.")


@app.command()
def rollback(
    ctx: typer.Context,
    steps: Annotated[int, typer.Option(min=1, help="How many migrations to undo.")] = 1,
    force: ForceOption = False,
) -> None:
    """Undo the most recent migration(s)."""
    target: DbTarget = ctx.obj
    header(target, "Rolling back")
    refuse_protected(target, "roll back migrations on", force)
    config = migrations.alembic_config(target.url, quiet=True)
    with connect(target) as engine:
        before = state_or_fail(engine, config)
        if not before.applied:
            success("Nothing to roll back.")
            return
        steps = min(steps, len(before.applied))
        confirm_destructive(target, f"roll back {steps} migration(s) on", force)
        migrations.downgrade(config, f"-{steps}")
        after = state_or_fail(engine, config)
        print_revisions(reversed(before.applied[len(after.applied):]), "Reverted")
        success(f"Rolled back to [cyan]{after.current or 'base'}[/cyan].")


@app.command()
def reset(ctx: typer.Context, force: ForceOption = False) -> None:
    """Undo every migration by running each downgrade."""
    target: DbTarget = ctx.obj
    header(target, "Resetting")
    refuse_protected(target, "undo every migration on", force)
    config = migrations.alembic_config(target.url, quiet=True)
    with connect(target) as engine:
        before = state_or_fail(engine, config)
        if not before.applied:
            success("Nothing to reset.")
            return
        confirm_destructive(target, "undo every migration on", force)
        migrations.downgrade(config, "base")
        print_revisions(reversed(before.applied), "Reverted")
        success("All migrations reverted.")


@app.command("make-migration")
def make_migration(
    ctx: typer.Context,
    message: Annotated[str, typer.Argument(help='Short description, e.g. "add badges".')],
    empty: Annotated[bool, typer.Option("--empty", help="Create a blank migration instead of autogenerating.")] = False,
) -> None:
    """Create a migration from model changes (review the file before applying)."""
    target: DbTarget = ctx.obj
    header(target, "Generating a migration against")
    config = migrations.alembic_config(target.url, quiet=True)
    with connect(target) as engine:
        state = state_or_fail(engine, config)
        if not empty and not state.up_to_date:
            fail(
                "Autogenerate compares models with the database, which has pending migrations.",
                hint="Run `kawika db migrate` first.",
            )
        if not empty:
            try:
                migrations.check(config)
            except AutogenerateDiffsDetected:
                pass
            else:
                fail(
                    "No model changes detected, so there is nothing to autogenerate.",
                    hint="Use --empty to write a data migration by hand.",
                )
        try:
            script = migrations.make_revision(config, message, autogenerate=not empty)
        except CommandError as exc:
            fail(str(exc))
    if script is None:
        fail("No migration was created.")
    success(f"Created [cyan]{script.revision}[/cyan]: {script.path}")
    info("Review it, then run `kawika db migrate`.")


@app.command()
def check(ctx: typer.Context) -> None:
    """Exit with an error if models have changes without a migration."""
    target: DbTarget = ctx.obj
    header(target, "Checking")
    config = migrations.alembic_config(target.url, quiet=True)
    with connect(target) as engine:
        state = state_or_fail(engine, config)
        if not state.up_to_date:
            fail("The database has pending migrations.", hint="Run `kawika db migrate` first.")
        try:
            migrations.check(config)
        except AutogenerateDiffsDetected as exc:
            fail(f"Models and migrations differ: {exc}", hint='Run `kawika db make-migration "..."`.')
    success("Models match the migrations.")
