"""Programmatic access to Alembic: config, state, and migration commands."""

import io
from dataclasses import dataclass

from alembic import command
from alembic.config import Config
from alembic.runtime.migration import MigrationContext
from alembic.script import Script, ScriptDirectory
from sqlalchemy import Engine

from app.core.config import SERVER_DIR


def alembic_config(database_url: str, *, quiet: bool = False) -> Config:
    """Alembic config pointed at `database_url` (no credentials in alembic.ini).

    `quiet` silences Alembic's own logging and console messages so the caller
    can report progress in its own words.
    """
    kwargs = {"stdout": io.StringIO()} if quiet else {}
    config = Config(str(SERVER_DIR / "alembic.ini"), **kwargs)
    config.set_main_option("script_location", str(SERVER_DIR / "migrations"))
    config.attributes["database_url"] = database_url
    config.attributes["configure_logger"] = not quiet
    return config


@dataclass(frozen=True)
class MigrationState:
    current: str | None
    head: str | None
    applied: list[Script]
    pending: list[Script]

    @property
    def up_to_date(self) -> bool:
        return not self.pending


def migration_state(engine: Engine, config: Config) -> MigrationState:
    """Where the database is relative to the migration scripts, oldest first."""
    scripts = ScriptDirectory.from_config(config)
    with engine.connect() as connection:
        current = MigrationContext.configure(connection).get_current_revision()

    head = scripts.get_current_head()
    history = list(reversed(list(scripts.walk_revisions())))  # base -> head
    if current is None:
        return MigrationState(current, head, [], history)

    ids = [script.revision for script in history]
    if current not in ids:
        raise LookupError(
            f"The database is at revision {current}, which is not in migrations/versions. "
            "It was probably created from another branch."
        )
    split = ids.index(current) + 1
    return MigrationState(current, head, history[:split], history[split:])


def upgrade(config: Config, revision: str = "head") -> None:
    command.upgrade(config, revision)


def downgrade(config: Config, revision: str) -> None:
    command.downgrade(config, revision)


def make_revision(config: Config, message: str, *, autogenerate: bool) -> Script | None:
    result = command.revision(config, message=message, autogenerate=autogenerate)
    return result[0] if isinstance(result, list) else result


def check(config: Config) -> None:
    """Raise `alembic.util.AutogenerateDiffsDetected` if models and migrations differ."""
    command.check(config)
